### PR TITLE
update Ukrainian translation

### PR DESCRIPTION
**Pull request by VovaMobile**
This translation include update the translation of interface, fully translated documentation and manifest

### CODE REVIEW

**Comment by jmdaweb** [comment]
Hi,
Why have you added a separate manifest file? Translated manifest strings are taken from nvda.po.

**Comment by VovaMobile** [comment]
Hi, in generated from nvda.po manifest not translated description. If
necessary, I can delete the file or you can delete it if you have the
possibility.

2022-06-14 13:28 GMT+03:00, José Manuel Delicado ***@***.***>:

**Comment by VovaMobile** [comment]
Sorry,  i not using scons and the add-on template to manage
translation. New strings for translating i get with source code
(Poedit have this option).
If i make incorrect, please help me and give me links to information
about correct methods for translation.

2022-06-14 13:57 GMT+03:00, José Manuel Delicado ***@***.***>:

**Comment by VovaMobile** [comment]
Hi!
I'm using Github Desktop, I don't know how to use console git. But I
will try to do as you wrote.

2022-06-14 14:30 GMT+03:00, José Manuel Delicado ***@***.***>:

**Comment by jmdaweb** [comment]
Another solution, maybe easier: add buildVars.py as part of the source code you are scanning for translations.

**Review by jmdaweb — APPROVED** [review]

**Comment by hxebolax** [comment]
Hello @ VovaMobile

Let me thank you for your cooperation. I have just accepted the changes and by the end of the month I plan to release a bugfixed version.

I'm really busy before that.

In this version will come the changes of your translations.

Meanwhile as I said @ jmdaweb you can use the plugin that I generate from the repo.

Thank you very much again.

**Comment by VovaMobile** [comment]
I thank You for Your addon and @jmdaweb for useful information about
correct translating!

2022-06-14 21:05 GMT+03:00, hxebolax ***@***.***>:

**Pull request merged**
